// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _1.dal.DAODbContext;

namespace _1.dal.Migrations
{
    [DbContext(typeof(DAOTeam06DbContext))]
    partial class DAOTeam06DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("_1.dal.Table.ChucVu", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ma")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ten")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.ToTable("ChucVu");
                });

            modelBuilder.Entity("_1.dal.Table.HoaDon", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("idNv")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ma")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("ngTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ngThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<int>("tinhTrang")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("idNv");

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("_1.dal.Table.HoaDonChiTiet", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("idHd")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("idSp")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("soLuong")
                        .HasColumnType("int");

                    b.Property<decimal>("thanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id");

                    b.HasIndex("idHd");

                    b.HasIndex("idSp");

                    b.ToTable("HoaDonChiTiet");
                });

            modelBuilder.Entity("_1.dal.Table.LoaiSanPham", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ma")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ten")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.ToTable("LoaiSanPham");
                });

            modelBuilder.Entity("_1.dal.Table.NhanVien", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("diaChi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("gioiTinh")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ho")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("idCv")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ma")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("ngSinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("quocGia")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("sdt")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ten")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("tenDem")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("thanhPho")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("trangThai")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("idCv");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("_1.dal.Table.SanPham", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("giaBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("idLsp")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ma")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ten")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.HasIndex("idLsp");

                    b.ToTable("SanPham");
                });

            modelBuilder.Entity("_1.dal.Table.HoaDon", b =>
                {
                    b.HasOne("_1.dal.Table.NhanVien", "nhanViens")
                        .WithMany("HoaDons")
                        .HasForeignKey("idNv")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("nhanViens");
                });

            modelBuilder.Entity("_1.dal.Table.HoaDonChiTiet", b =>
                {
                    b.HasOne("_1.dal.Table.HoaDon", "hoaDons")
                        .WithMany("HoaDonCts")
                        .HasForeignKey("idHd")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_1.dal.Table.SanPham", "sanPhams")
                        .WithMany("HoaDonCts")
                        .HasForeignKey("idSp")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("hoaDons");

                    b.Navigation("sanPhams");
                });

            modelBuilder.Entity("_1.dal.Table.NhanVien", b =>
                {
                    b.HasOne("_1.dal.Table.ChucVu", "chucVu")
                        .WithMany("NhanViens")
                        .HasForeignKey("idCv")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("chucVu");
                });

            modelBuilder.Entity("_1.dal.Table.SanPham", b =>
                {
                    b.HasOne("_1.dal.Table.LoaiSanPham", "loaiSps")
                        .WithMany("SanPhams")
                        .HasForeignKey("idLsp")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("loaiSps");
                });

            modelBuilder.Entity("_1.dal.Table.ChucVu", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("_1.dal.Table.HoaDon", b =>
                {
                    b.Navigation("HoaDonCts");
                });

            modelBuilder.Entity("_1.dal.Table.LoaiSanPham", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("_1.dal.Table.NhanVien", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("_1.dal.Table.SanPham", b =>
                {
                    b.Navigation("HoaDonCts");
                });
#pragma warning restore 612, 618
        }
    }
}
